/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: 
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef MYCROFTPLASMOID_DBUS_H
#define MYCROFTPLASMOID_DBUS_H

#include <QObject>
#include <QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.kde.mycroftapplet
 */
class MycroftDbusAdapterInterface: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.mycroftapplet")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.mycroftapplet\">\n"
"    <signal name=\"sendShowMycroft\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"msgShowMycroft\"/>\n"
"    </signal>\n"
"    <signal name=\"sendShowSkills\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"msgShowSkills\"/>\n"
"    </signal>\n"
"    <signal name=\"sendShowInstallSkills\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"msgShowInstallSkills\"/>\n"
"    </signal>\n"
"    <method name=\"showMycroft\"/>\n"
"    <method name=\"showSkills\"/>\n"
"    <method name=\"showSkillsInstaller\"/>\n"
"  </interface>\n"
        "")
public:
    MycroftDbusAdapterInterface(QObject *parent);
    virtual ~MycroftDbusAdapterInterface();
    Q_INVOKABLE QString getMethod(const QString &method);

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void showMycroft();
    void showSkills();
    void showSkillsInstaller();
Q_SIGNALS: // SIGNALS
    void sendShowInstallSkills(const QString &msgShowInstallSkills);
    void sendShowMycroft(const QString &msgShowMycroft);
    void sendShowSkills(const QString &msgShowSkills);
};

#endif
